on: repository_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    # curl -X POST -H "Authorization: token ${TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" https://api.github.com/repos/anemyte/ci-test/dispatches --data '{"event_type":"test","client_payload":{"msg":"Hello, world!"}}'
    steps:
      - uses: actions/checkout@v2
      - name: Print Payload
        if: github.action == 'print'
        run: |
          echo '${{ toJson(github.event.client_payload) }}'
      - name: Say Hello
        if: github.action == 'hello'
        run: |
          echo 'Hello, world!'
      - name: In Any Case
        run: |
          echo ${{ github.action }}
