name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'A message to echo'

env:
  MSG: wzup
  INPUT_MSG: ${{ github.event.inputs.msg }}

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Echo
      run: |
        MSG=${$INPUT_MSG:-$MSG}
        echo "Hello $MSG"
