name: Manual workflow

on:
  push: {}
  workflow_dispatch:
    inputs:
      msg:
        description: 'A message to echo'
        default: "This is a test"

env:
  MSG: ${{ github.event.inputs.msg || "wzup" }}
  #INPUT_MSG: 

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Echo
      run: |
        #MSG=${INPUT_MSG:-$MSG}
        echo "$MSG"
