name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'A message to echo'

env:
  MSG: wzup

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Echo
      run: |
        MSG=${${{ github.event.inputs.msg }}:-MSG}
        echo "Hello $MSG"
