name: Manual workflow

on:
  push: {}
  workflow_dispatch:
    inputs:
      msg:
        description: 'A message to echo'
        default: "This is a test"

env:
  MSG: ${{ github.event.inputs.msg || 'wzup' }}

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Echo
      run: |
        bash test1.sh
